<?php

namespace Database\Seeders;

use App\Models\Asset;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AssetSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $assets = [
            // Vehicles
            [
                'code' => 'VH001',
                'name' => 'Toyota Hilux Double Cabin',
                'description' => 'Pickup truck for field operations',
                'type' => 'vehicle',
                'brand' => 'Toyota',
                'model' => 'Hilux 2.4 VNT',
                'serial_number' => 'VH001-TOY-HIL-2023-001',
                'purchase_year' => 2023,
                'purchase_price' => 450000000,
                'status' => 'in_use',
                'location' => 'Site A - Jakarta',
                'assigned_to' => 4, // Dewi Lestari
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'VH002',
                'name' => 'Honda CR-V',
                'description' => 'SUV for supervisor transportation',
                'type' => 'vehicle',
                'brand' => 'Honda',
                'model' => 'CR-V 1.5 Turbo',
                'serial_number' => 'VH002-HON-CRV-2023-002',
                'purchase_year' => 2023,
                'purchase_price' => 550000000,
                'status' => 'available',
                'location' => 'Head Office - Jakarta',
                'assigned_to' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'VH003',
                'name' => 'Suzuki Carry Pickup',
                'description' => 'Light pickup for logistics',
                'type' => 'vehicle',
                'brand' => 'Suzuki',
                'model' => 'Carry 1.5 FD',
                'serial_number' => 'VH003-SUZ-CAR-2022-003',
                'purchase_year' => 2022,
                'purchase_price' => 180000000,
                'status' => 'maintenance',
                'location' => 'Workshop - Jakarta',
                'assigned_to' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Equipment
            [
                'code' => 'EQ001',
                'name' => 'Generator Set 5000 VA',
                'description' => 'Portable generator for backup power',
                'type' => 'equipment',
                'brand' => 'Yamaha',
                'model' => 'EF1000iS',
                'serial_number' => 'EQ001-YAM-GEN-2023-001',
                'purchase_year' => 2023,
                'purchase_price' => 25000000,
                'status' => 'available',
                'location' => 'Warehouse - Jakarta',
                'assigned_to' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'EQ002',
                'name' => 'Water Pump 2 Inch',
                'description' => 'Submersible water pump for site operations',
                'type' => 'equipment',
                'brand' => 'Shimizu',
                'model' => 'PC-268BIT',
                'serial_number' => 'EQ002-SHI-PUM-2023-002',
                'purchase_year' => 2023,
                'purchase_price' => 8500000,
                'status' => 'in_use',
                'location' => 'Site B - Surabaya',
                'assigned_to' => 7, // Eko Prasetyo
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'EQ003',
                'name' => 'Compressor 10 HP',
                'description' => 'Air compressor for pneumatic tools',
                'type' => 'equipment',
                'brand' => 'Krisbow',
                'model' => 'KW10-100',
                'serial_number' => 'EQ003-KRI-COM-2022-003',
                'purchase_year' => 2022,
                'purchase_price' => 15000000,
                'status' => 'in_use',
                'location' => 'Workshop - Jakarta',
                'assigned_to' => 5, // Rudi Hermawan
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Electronics
            [
                'code' => 'EL001',
                'name' => 'Laptop Dell Latitude 5420',
                'description' => 'Business laptop for software development',
                'type' => 'electronics',
                'brand' => 'Dell',
                'model' => 'Latitude 5420',
                'serial_number' => 'EL001-DEL-LAT-2023-001',
                'purchase_year' => 2023,
                'purchase_price' => 18500000,
                'status' => 'in_use',
                'location' => 'IT Department',
                'assigned_to' => 1, // Ahmad Pratama
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'EL002',
                'name' => 'Laptop HP ProBook 440',
                'description' => 'Business laptop for finance operations',
                'type' => 'electronics',
                'brand' => 'HP',
                'model' => 'ProBook 440 G9',
                'serial_number' => 'EL002-HP-PRO-2023-002',
                'purchase_year' => 2023,
                'purchase_price' => 16500000,
                'status' => 'in_use',
                'location' => 'Finance Department',
                'assigned_to' => 3, // Budi Santoso
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'EL003',
                'name' => 'iPad Air 5th Gen',
                'description' => 'Tablet for field operations and presentations',
                'type' => 'electronics',
                'brand' => 'Apple',
                'model' => 'iPad Air 5th Gen 64GB',
                'serial_number' => 'EL003-APP-IPA-2023-003',
                'purchase_year' => 2023,
                'purchase_price' => 8500000,
                'status' => 'available',
                'location' => 'Marketing Department',
                'assigned_to' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'EL004',
                'name' => 'iPhone 14 Pro',
                'description' => 'Company phone for supervisor',
                'type' => 'electronics',
                'brand' => 'Apple',
                'model' => 'iPhone 14 Pro 128GB',
                'serial_number' => 'EL004-APP-IP4-2023-004',
                'purchase_year' => 2023,
                'purchase_price' => 18999000,
                'status' => 'in_use',
                'location' => 'Operations Department',
                'assigned_to' => 4, // Dewi Lestari
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Furniture
            [
                'code' => 'FR001',
                'name' => 'Ergonomic Office Chair',
                'description' => 'Executive office chair with lumbar support',
                'type' => 'furniture',
                'brand' => 'Chitose',
                'model' => 'Miyako High Back',
                'serial_number' => 'FR001-CHI-MIY-2023-001',
                'purchase_year' => 2023,
                'purchase_price' => 3500000,
                'status' => 'in_use',
                'location' => 'Manager Office',
                'assigned_to' => 2, // Siti Nurhaliza
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'FR002',
                'name' => 'Executive Desk',
                'description' => 'Large wooden executive desk',
                'type' => 'furniture',
                'brand' => 'Vanda',
                'model' => 'Executive Series E-120',
                'serial_number' => 'FR002-VAN-EXE-2023-002',
                'purchase_year' => 2023,
                'purchase_price' => 4500000,
                'status' => 'in_use',
                'location' => 'Finance Office',
                'assigned_to' => 3, // Budi Santoso
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'FR003',
                'name' => 'Meeting Table 8 Seats',
                'description' => 'Large meeting table for conference room',
                'type' => 'furniture',
                'brand' => 'Olympic',
                'model' => 'Conference Series C-200',
                'serial_number' => 'FR003-OLY-CON-2022-003',
                'purchase_year' => 2022,
                'purchase_price' => 8500000,
                'status' => 'available',
                'location' => 'Conference Room',
                'assigned_to' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'FR004',
                'name' => 'Filing Cabinet 4 Drawers',
                'description' => 'Metal filing cabinet for document storage',
                'type' => 'furniture',
                'brand' => 'Brother',
                'model' => 'BFC-4D',
                'serial_number' => 'FR004-BRO-FIL-2023-004',
                'purchase_year' => 2023,
                'purchase_price' => 2200000,
                'status' => 'available',
                'location' => 'HR Department',
                'assigned_to' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Other
            [
                'code' => 'OT001',
                'name' => 'Projector Epson EB-X41',
                'description' => 'Projector for presentations and meetings',
                'type' => 'other',
                'brand' => 'Epson',
                'model' => 'EB-X41',
                'serial_number' => 'OT001-EPS-PRO-2023-001',
                'purchase_year' => 2023,
                'purchase_price' => 7500000,
                'status' => 'in_use',
                'location' => 'Conference Room',
                'assigned_to' => 6, // Indah Permata
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'OT002',
                'name' => 'Coffee Machine DeLonghi',
                'description' => 'Automatic coffee machine for office pantry',
                'type' => 'other',
                'brand' => 'DeLonghi',
                'model' => 'Magnifica S ECAM 22.110.B',
                'serial_number' => 'OT002-DEL-COF-2023-002',
                'purchase_year' => 2023,
                'purchase_price' => 4500000,
                'status' => 'retired',
                'location' => 'Storage',
                'assigned_to' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        Asset::insert($assets);
    }
}